nelmio_api_doc:
    documentation:
        info:
            title: TagFlow API
            description: API de la red social TagFlow
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

        security:
            - Bearer: []

    areas:
        default:
            path_patterns:
                - ^/tagflow